name: my-first-workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world step
        uses: ./.github/actions/hello-world-action
        id: hello
        with:
          who-to-greet: 'Revelator IO24'
        
